In [12]:
import pandas as pd
import numpy as np

data = pd.read_csv("microsoft_sep2017.csv")

In [2]:
data.head()

,Doc currency,USD,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9,Unnamed: 10
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A/C/D/U,Valid-From Date,Valid To Date,Offer Display Name,Offer ID,License Agreement Type,Purchase Unit,Secondary License Type,End Customer Type,List Price,ERP Price
2,ADD,20170901,99991231,Windows 10 Enterprise E3,39504991-553b-48c2-bdf4-ea47f93bf784,Corporate,1 Month(s),NON-SPECIFIC,CLOUD RESELLER CORPORATE,9.60,12.00
3,NaN,NaN,NaN,Windows 10 Enterprise E3 VDA,4b608b64-3a27-4373-854c-fd33115a8ce1,Corporate,1 Month(s),NON-SPECIFIC,CLOUD RESELLER CORPORATE,14.40,18.00
4,NaN,NaN,NaN,Windows 10 Enterprise E5,f2c42110-ec7b-4434-b55e-1a9e456ac2f0,Corporate,1 Month(s),NON-SPECIFIC,CLOUD RESELLER CORPORATE,15.20,19.00

In [13]:
data.columns=data.loc[1]

In [14]:
data.head()

1,A/C/D/U,Valid-From Date,Valid To Date,Offer Display Name,Offer ID,License Agreement Type,Purchase Unit,Secondary License Type,End Customer Type,List Price,ERP Price
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,A/C/D/U,Valid-From Date,Valid To Date,Offer Display Name,Offer ID,License Agreement Type,Purchase Unit,Secondary License Type,End Customer Type,List Price,ERP Price
2,ADD,20170901,99991231,Windows 10 Enterprise E3,39504991-553b-48c2-bdf4-ea47f93bf784,Corporate,1 Month(s),NON-SPECIFIC,CLOUD RESELLER CORPORATE,9.60,12.00
3,NaN,NaN,NaN,Windows 10 Enterprise E3 VDA,4b608b64-3a27-4373-854c-fd33115a8ce1,Corporate,1 Month(s),NON-SPECIFIC,CLOUD RESELLER CORPORATE,14.40,18.00
4,NaN,NaN,NaN,Windows 10 Enterprise E5,f2c42110-ec7b-4434-b55e-1a9e456ac2f0,Corporate,1 Month(s),NON-SPECIFIC,CLOUD RESELLER CORPORATE,15.20,19.00

In [15]:
data = data[['Offer Display Name', 'End Customer Type']]

In [16]:
data.head()

1            Offer Display Name         End Customer Type
0                           NaN                       NaN
1            Offer Display Name         End Customer Type
2      Windows 10 Enterprise E3  CLOUD RESELLER CORPORATE
3  Windows 10 Enterprise E3 VDA  CLOUD RESELLER CORPORATE
4      Windows 10 Enterprise E5  CLOUD RESELLER CORPORATE

In [17]:
data.columns = ['category', 'name']

In [18]:
data['name'] = "Microsoft"

                       category                      name
0                           NaN                       NaN
1            Offer Display Name         End Customer Type
2      Windows 10 Enterprise E3  CLOUD RESELLER CORPORATE
3  Windows 10 Enterprise E3 VDA  CLOUD RESELLER CORPORATE
4      Windows 10 Enterprise E5  CLOUD RESELLER CORPORATE

In [22]:
data.fillna(value='', axis=1, inplace=True)

In [25]:
data = data.loc[["(Government Pricing)" not in d for d in data['category']]]

In [30]:
data = data.loc[["Gov" not in d for d in data['category']]]

In [32]:
data = data.loc[1:]

In [39]:
for index,row in data.iterrows():
    if 'Azure' in row['category']:
        data.loc[index,'name'] = "Microsoft Azure"
    elif 'Dynamics 365' in row['category'] or 'Dyn365' in row['category']:
        data.loc[index,'name'] = "Dynamics 365"
    elif 'Office 365' in row['category']:
        data.loc[index,'name'] = "Office 365"
    else:
        data.loc[index,'name'] = "other_microsoft"

C:\Users\Asus\Anaconda3\envs\som_env\lib\site-packages\ipykernel\__main__.py:9: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Asus\Anaconda3\envs\som_env\lib\site-packages\ipykernel\__main__.py:3: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  app.launch_new_instance()
C:\Users\Asus\Anaconda3\envs\som_env\lib\site-packages\ipykernel\__main__.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
C:\Users\Asus\Anaconda3\envs\som_env\lib\site-packages\ipykernel\__main__.py:7: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy

In [38]:
data.loc[data['name'] == "other_microsoft"]

                                              category   name
1                                   Offer Display Name  other
2                             Windows 10 Enterprise E3  other
3                         Windows 10 Enterprise E3 VDA  other
4                             Windows 10 Enterprise E5  other
156                           Windows 10 Enterprise E5  other
157  Additional PSTN numbers to extend Skype for Bu...  other
173                                   Customer Lockbox  other
174                       Customer Lockbox for faculty  other
175                      Customer Lockbox for students  other
176                                    Delve Analytics  other
177                        Delve Analytics for faculty  other
178                       Delve Analytics for students  other
448                  Enterprise Mobility + Security E3  other
449      Enterprise Mobility + Security E3 for Faculty  other
450     Enterprise Mobility + Security E3 for Students  other
451                  Enterprise Mobility + Security E5  other
452      Enterprise Mobility + Security E5 for Faculty  other
453     Enterprise Mobility + Security E5 for Students  other
454                           Exchange Online (Plan 1)  other
455                           Exchange Online (Plan 2)  other
456        Exchange Online Advanced Threat Protection   other
457  Exchange Online Advanced Threat Protection for...  other
458  Exchange Online Advanced Threat Protection for...  other
459  Exchange Online Archiving (EOA) for Exchange S...  other
460      Exchange Online Archiving for Exchange Online  other
461                              Exchange Online Kiosk  other
462                         Exchange Online Protection  other
463                    Flow Additional Runs per 50,000  other
465        Flow Additional Runs per 50,000 for Faculty  other
467       Flow Additional Runs per 50,000 for Students  other
..                                                 ...    ...
564     PowerApps Professional Environment for Faculty  other
566    PowerApps Professional Environment for Students  other
568                                     Project Online  other
569                          Project Online Essentials  other
570                             Project Online Premium  other
571                        Project Online Professional  other
574                         SharePoint Online (Plan 1)  other
575                         SharePoint Online (Plan 2)  other
576                       Skype for Business Cloud PBX  other
577           Skype for Business Cloud PBX for faculty  other
578          Skype for Business Cloud PBX for students  other
579                 Skype for Business Online (Plan 1)  other
580                 Skype for Business Online (Plan 2)  other
581                        Skype for Business Plus CAL  other
582            Skype for Business Plus CAL for faculty  other
583           Skype for Business Plus CAL for students  other
584               Skype for Business PSTN Conferencing  other
585  Skype for Business PSTN Conferencing for E5 wi...  other
586  Skype for Business PSTN Conferencing for E5 wi...  other
587  Skype for Business PSTN Conferencing for E5 wi...  other
588   Skype for Business PSTN Conferencing for faculty  other
589  Skype for Business PSTN Conferencing for students  other
590  Skype for Business PSTN Domestic and Internati...  other
591  Skype for Business PSTN Domestic and Internati...  other
592  Skype for Business PSTN Domestic and Internati...  other
593           Skype for Business PSTN Domestic Calling  other
594  Skype for Business PSTN Domestic Calling for f...  other
595  Skype for Business PSTN Domestic Calling for s...  other
597                           Windows 10 Enterprise E3  other
598                                  Yammer Enterprise  other

[110 rows x 2 columns]